server:
  port: 8003

spring:
  application:
    name: edu-service-course

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册

# mybatis 配置信息
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

# 日志输出
logging:
  level:
    com.oes: info
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log