server:
  port: 8005

spring:
  application:
    name: edu-service-organization
  profiles:
    active: common

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册