server:
  port: 8002
spring:
  application:
    name: edu-service-msm
    # redis配置
  redis:
    database: 0
    host: 139.129.101.91
    port: 8085
    password: Xkj_13011301
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        max-idle: 8
        min-idle: 0

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    feth-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: msm #实例名
    prefer-ip-address: true

