server:
  port: 8010

spring:
  application:
    name: edu-service-payment

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册

# mybatis 配置信息
mybatis:
  mapper-locations: classpath:mapper/*.xml

