server:
  port: 9527
  #跳过认证的路由
  skip-auth-urls: /user/login

spring:
  application:
    name: edu-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://edu-service-usercenter
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

            # 服务降级  触发调用 HystrixFallbackHandler GatewayFallbackConfig
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/defaultfallback'

        - id: test1
          uri: lb://edu-authentication
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: edu-authentication
          uri: lb://edu-authentication  # 后端服务名
          predicates:
            - Path=/loginUser

        - id: edu-service-usercenter
          uri: lb://edu-service-usercenter
          predicates:
            - Path=/user/**          #断言，路径相匹配的进行路由
          filters:
            - JwtCheck

        - id: edu-course #课程模块8003
          uri: lb://edu-service-course
          predicates:
            - Path=/course/**
          filters:
            # 服务降级  触发调用 HystrixFallbackHandler GatewayFallbackConfig
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/defaultfallback'

        - id: edu-organization # 机构模块8006
          uri: lb://edu-service-organization
          predicates:
            - Path=/organization/**

        - id: edu-student # 学生模块8007
          uri: lb://edu-service-student
          predicates:
            - Path=/student/**

        - id: edu-shopping #商品模8009
          uri: lb://edu-service-shopping
          predicates:
            - Path=/courseMer/** #课程商品管理

        - id: edu-shopping #商品模8009
          uri: lb://edu-service-shopping
          predicates:
            - Path=/merchandise/** #商品管理

        - id: edu-shopping #商品模8009
          uri: lb://edu-service-shopping
          predicates:
            - Path=/order/** #订单管理

        - id: edu-shopping #商品模8009
          uri: lb://edu-service-shopping
          predicates:
            - Path=/shoppingCart/** #购物车管理

        - id: edu-shopping #商品模8009
          uri: lb://edu-service-shopping
          predicates:
            - Path=/payment/** #支付管理

        - id: edu-payment # 支付模块8010
          uri: lb://edu-service-payment
          predicates:
            - Path=//transaction/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://172.20.0.12:9401/rsa/publicKey' #配置RSA的公钥访问地址

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册

secure:
  ignore:
    urls: #配置白名单路径
      - "/auth/oauth/token"