server:
  port: 3344

spring:
  application:
    name: edu-config-center
  cloud:
    config:
      server:
        git:
          uri: http://192.168.4.251/wangxingxing/springcloud-config.git # github上面的git仓库名字
          search-paths:
            - springcloud-config # 搜索目录
          username: wangxingxing
          password: 12345678
      label: master #读取分支

eureka:
  client:
    service-url:
      defaultZone: http://172.20.0.10:7001/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名
    prefer-ip-address: true  #是否使用IP地址注册
